wandb_version: 1

wandb:
  desc: null
  value: true
name:
  desc: null
  value: lstm-enc-dec-inp-144-144-7540309np
num_features:
  desc: null
  value: 11
hidden_size:
  desc: null
  value: 256
dropout:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0
input_window:
  desc: null
  value: 144
output_window:
  desc: null
  value: 144
learning_rate:
  desc: null
  value: 0.0005
num_layers:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 40
batch_size:
  desc: null
  value: 256
train_data_len:
  desc: null
  value: 52704
training_prediction:
  desc: null
  value: recursive
loss_type:
  desc: null
  value: RMSE
model_label:
  desc: null
  value: ENC-DEC
teacher_forcing_ratio:
  desc: null
  value: 0.5
dynamic_tf:
  desc: null
  value: true
shuffle:
  desc: null
  value: true
one_hot_month:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.8
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694370646.593544
    t:
      1:
      - 1
      - 5
      - 6
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.15.8
      8:
      - 5
